### PR TITLE
Add the exclusive keyword

### LINKED ISSUE #44: Exclusive keyword
## Exclusive keyword

During the app initialization the subsite will automatically generate a keyword named `subsite_exclusive`. Each resource with this keyword assigned, will be escluded from the global catalogue (this is valid also for the API/v2 `/resources`, `/datasets`, `/documents`, `/maps`, `/geoapps` )

**NOTE:** The `subsite_exclusive` keyword is used to exclude a resource from the global catalog. This keyword is commonly applied to all resources. If a resource needs to be accessible only within a specific subsite, utilize the additional configuration provided by that subsite to filter it out from other subsites.

For example:

```
resource1 -> no keyword
resource2 -> keyword1 assinged
resource3 -> subsite_exclusive keyword assigned

Call -> http://localhost:8000/#/
    - will return resource1 and resource2
```

Via API/v2 `/resources`, `/datasets`, `/documents`, `/maps`, `/geoapps` is possible to return all the value even if the `subsite_exclusive` keyword is set
For example:

```
resource1 -> no keyword
resource2 -> keyword1 assinged
resource3 -> subsite_exclusive keyword assigned

Call -> http://localhost:8000/api/v2/resources/
    - will return resource1 and resource2

    
Call -> http://localhost:8000/api/v2/resources/?return_all=true
    - will return resource1, resource2 and resource3
```

### PR DESCRIPTION
**Pull request by mattiagiupponi**
ref #44

### CODE REVIEW

**Comment by gannebamm** [comment]
Thanks for the fast work @mattiagiupponi !
We have deployed the changes and it is starting properly. @vineetasharma105 is currently reviewing its functionality.

**Comment by vineetasharma105** [comment]
Hi,
I am facing a question when dealing with subsite exclusive contents.
Question : Why the subsite exclusive contents , redirected via the linked resources click, still points towards and redirects to the homepage of geonode and the user is not anymore on the subsite page?
Enhancement/Requirement : as a user and as an admin also, the linked resources should not redirect to the homepage and rather stay on the subsite page, as the contents are 'subsite specific'.

As can be seen in the screen shot, the map (subsite_exclusive_test_map)  and its related data set (subsite_exclusive_test_data)
image are part of Holisoils subsite and the keyword and the group is set up accordingly. Still , the linked resources links points to the homepage.
Map : https://geonode-demo.thuenen.de/holisoils/catalogue/uuid/20e4d7c5-09fd-46ab-843b-f1bbb4bfee8d
dataset : https://geonode-demo.thuenen.de/catalogue/uuid/ac3361f8-8299-43de-a4f7-20d51a6c7c01
Subsitelink: https://geonode-demo.thuenen.de/holisoils/#/

**Comment by gannebamm** [comment]
I just deployed the changes and they do not work as intended, yet.

See: https://geonode-demo.thuenen.de/holisoils/catalogue/uuid/6e60d107-3643-4ce5-9482-e098ad4e9305

The map is subsite exlusive, belongs to the holisoils group and uses only subsite ressources. It seems all ressources which are subsite_exclusive currently fail with: `[ "Subsite not found" ]` for a request like https://geonode-demo.thuenen.de/de-de/api/v2/datasets/22?api_preset=viewer_common&api_preset=dataset_viewer

We used these subsite specific variables:
```python
# SUBSITE SPECIFIC CONFIGURATION
ENABLE_SUBSITE_CUSTOM_THEMES = True
ENABLE_CATALOG_HOME_REDIRECTS_TO = False
SUBSITE_READ_ONLY = False # return download_resourcebase and view resourcebase as permissions
SUBSITE_HIDE_EXCLUSIVE_FROM_SPECIFIC_API = True # If TRUE will hide the `subsite_exclusive` resources also from the detailed endpoint `/documents`, `/maps`, `/datasets`, '/geoapps`
```

The code is using https://github.com/geosolutions-it/geonode-subsites/pull/45/commits/270c34958cf69dd459877fa63d89fbe2bb2cfc43 

Did we misconfigure something?

**Comment by mattiagiupponi** [comment]
Can you try by set `SUBSITE_HIDE_EXCLUSIVE_FROM_SPECIFIC_API = False` ?

**Comment by gannebamm** [comment]
> Can you try by set `SUBSITE_HIDE_EXCLUSIVE_FROM_SPECIFIC_API = False` ?

This will fix the [ "Subsite not found" ] issue but the links still point to the main portal.

**Comment by mattiagiupponi** [comment]
uhm is working fine on my test environment with or without that variable, i'll give another check soon

**Comment by gannebamm** [comment]
Just as additional info:
We use this deployment https://github.com/Thuenen-GeoNode-Development/thuenen_atlas/tree/subsite_exclusive_test
Which is based on the docker blueprint plus some of our contrib apps. It will use the subsite dev branch as listed here: https://github.com/Thuenen-GeoNode-Development/thuenen_atlas/commit/4183280dd91ecea556610cf9f5bab1593ef6786a

**Comment by mattiagiupponi** [comment]
Hi @gannebamm 
I made some local test using the project you linked and as you mentioned, the linked resources still point the main catalogue:
image

But the API v2 is returning the linked resources as expected by adding the subsite:

image

While on my local instance using geonode-master and mapstore-client-master is working as expected:

image


I notice that the mapstore-client used by the project, is a fork of the 52north mapstore client fork which is about 60 commits behind the production one for GeoNode 4.3.x (~20 commits behing) which also includes improvement for the linked resources (https://github.com/GeoNode/geonode-mapstore-client/commit/c7f6d10eeb52543f9669c2d1d20cd55f7851f28f)

Can you please evaluate to upgrade the mapstore client and align it to the GeoNode one? So we can have the same environment.

**Comment by mattiagiupponi** [comment]
As counterproof, i run a geonode 433 on my local instance and the subsite is correctly used for the linked resources:
image

**Comment by gannebamm** [comment]
@mattiagiupponi Thank you very much for the in-depth look! Yes, we will upgrade soon. See: https://github.com/Thuenen-GeoNode-Development/thuenen_atlas/issues/58#issuecomment-2490793327

**Comment by gannebamm** [comment]
We have deployed a new version and most parts of the feature do work well but ressources with subsite_exclusive keyword will fail with the known [ "Subsite not found" ] error. See:

https://geonode-demo.thuenen.de/holisoils/catalogue/#/?d=36%3Bdataset%3Bvector

If `SUBSITE_HIDE_EXCLUSIVE_FROM_SPECIFIC_API = False` they will render. Can you please take a look again @mattiagiupponi

**Comment by ridoo** [comment]
@mattiagiupponi A quick test turns out that there are different URLs in the `Add Resource` drop down depending on either opening subsite root `http://172.18.0.1:8001/holisoils/` or the catalogue `http://172.18.0.1:8001/holisoils/catalogue/`. The subsite root point to `http://172.18.0.1:8001/holisoils/catalogue/#/map/new` and the subsite's catalogue points to `http://172.18.0.1:8001/catalogue/#/map/new` instead.

Also, what I can see from the Django Logs (not sure if this is related):

```
WARNING Forbidden: /api/v2/executionrequest
WARNING Forbidden: /api/v2/executionrequest
WARNING "GET /api/v2/executionrequest?filter%7Baction%7D=import&filter%7Bsource%7D=upload&page=1&page_size=99999 HTTP/1.1" 403 103
WARNING "GET /api/v2/executionrequest?filter%7Baction%7D=import&filter%7Bsource%7D=upload&page=1&page_size=99999 HTTP/1.1" 403 103
```

However, creating a map starting from subsite's catalogue will create a map but redirect (http://172.18.0.1:8001/holisoils/api/v2/maps/9/?api_preset=viewer_common&api_preset=map_viewer) fails with `404`. Maps are available from the main portal.

@gannebamm I did not spot errors like `[ "Subsite not found" ]`. Which component

**Comment by gannebamm** [comment]
@ridoo We are currently working on the subsite_exclusive feature. This has currently no effect on creating new ressources on the subsite. In our workflow ressources are added by main portals staff via the main portal (atlas in our case). They will be tagged with the keyword `subsite_exclusive` to only show on the subsite, if they are project specific and not data created by ourselves. For that we need them to not show up in the main catalogue (works) but show up in the subsite catalogue (works) and showing correct links on the subsite for linked ressources (also works). But they still show up on the main portals API if `SUBSITE_HIDE_EXCLUSIVE_FROM_SPECIFIC_API = False`. If we change this to `SUBSITE_HIDE_EXCLUSIVE_FROM_SPECIFIC_API = True` they will not show up in the main portals API, but the rendering of ressource panals is broken.

> I did not spot errors like [ "Subsite not found" ]. Which component is logging such errors?

It is a mapstore call to fetch info for the ressource info panel. See this:
- https://geonode-demo.thuenen.de/holisoils/catalogue/#/?d=36%3Bdataset%3Bvector
- will try to fetch info via https://geonode-demo.thuenen.de/de-de/api/v2/datasets/36?api_preset=viewer_common&api_preset=dataset_viewer
- which will result in this JSON answer `{"success":false,"errors":["Subsite not found"],"code":"not_found"}`

If you do the same request for a dataset on the subsite **which is not** tagged as `subsite_exclusive` it will render properly. See:

- https://geonode-demo.thuenen.de/holisoils/catalogue/#/?d=33%3Bdataset%3Braster
- will trigger https://geonode-demo.thuenen.de/api/v2/datasets/33?api_preset=viewer_common&api_preset=dataset_viewer
- which will answer JSON
```json
{
    "dataset": {
        "uuid": "0ea54778-63a2-4bf9-b684-51d41e29f1a9",
        "default_style": {
            "pk": 14,
            "name": "ph_30_100",
            "workspace": "geonode",
            "sld_title": "ph_30_100",
            "sld_url": "https://geonode-demo.thuenen.de/geoserver/rest/workspaces/geonode/styles/ph_30_100.sld"
        }
        // [... whole API v2 response ...]
    }
}
```

the main portals API will properly hide subsite exclusive datasets:
https://geonode-demo.thuenen.de/api/v2/datasets/

while the subsite will show those:
https://geonode-demo.thuenen.de/holisoils/api/v2/datasets/

**Comment by mattiagiupponi** [comment]
Hi @gannebamm @ridoo 
Sorry but i was submerged with other tasks, today I'll take a look on your questions.

> If SUBSITE_HIDE_EXCLUSIVE_FROM_SPECIFIC_API = False they will render. Can you please take a look again @mattiagiupponi

I'm going to take a look now.

**Comment by mattiagiupponi** [comment]
Hi @gannebamm 
The last push should fix the issue related to the visualization of the resources inside a subsite. Even with `SUBSITE_HIDE_EXCLUSIVE_FROM_SPECIFIC_API = True` it should be rendered correctly now
Can you please verify?

**Comment by gannebamm** [comment]
> The last push should fix the issue related to the visualization of the resources inside a subsite. Even with SUBSITE_HIDE_EXCLUSIVE_FROM_SPECIFIC_API = True it should be rendered correctly now
Can you please verify?

We are currently starting the review. First look is promising and the issue with subsite exclusive ressources like
- https://geonode-demo.thuenen.de/holisoils/catalogue/#/?d=36%3Bdataset%3Bvector

seems to be solved

**Comment by mattiagiupponi** [comment]
> @mattiagiupponi can you please double check if this is related: [Thuenen-GeoNode-Development/thuenen_atlas#58 (comment)](https://github.com/Thuenen-GeoNode-Development/thuenen_atlas/issues/58#issuecomment-2507947635)

there was a missing slash in the beginning of the URL, so for the remote service was appending the embed url to the main one instead of recreating one. now should be fixed. please try again

**Comment by mattiagiupponi** [comment]
> @mattiagiupponi A quick test turns out that there are different URLs in the `Add Resource` drop down depending on either opening subsite root `http://172.18.0.1:8001/holisoils/` or the catalogue `http://172.18.0.1:8001/holisoils/catalogue/`. The subsite root point to `http://172.18.0.1:8001/holisoils/catalogue/#/map/new` and the subsite's catalogue points to `http://172.18.0.1:8001/catalogue/#/map/new` instead.

I'm trying to replicate this, but it looks like is working as expected, only the remote-services are pointing to the main site root. as an instance:
issue_subsite

Could be this issue related to my previous comment? https://github.com/geosolutions-it/geonode-subsites/pull/45#issuecomment-2503576583 Can you please try with an updated version of GeoNode?
Anyway i'm going to check and fix the remote service that points to the main site.

Im also going to verify this:

> Also, what I can see from the Django Logs (not sure if this is related):

The upload from the subsite works fine to me, no 403 are returned. It could always be related to the GeoNode version (i guess)
image

Can you confirm @ridoo ?

**Comment by ridoo** [comment]
Hey @mattiagiupponi 

> Could be this issue related to my previous comment? https://github.com/geosolutions-it/geonode-subsites/pull/45#issuecomment-2503576583 Can you please try with an updated version of GeoNode?

The [version we use](https://github.com/Thuenen-GeoNode-Development/geonode-mapstore-client) should be up to date (more or less) with `v4.4.x`. Of course, we have made customizations.

I tested again and seems that your local overrides did not have any effect. We also provide an `overrideLocalConfig` in a `_geonode_config.html` and we should make sure to not only let the last one take precedence. It would be good to provide a recursive handling of all `overrideLocalConfigs`. I made it work via this configuration:

```
{% extends 'geonode-mapstore-client/_geonode_config.html' %}
{% block override_local_config %}

{% comment %} Keep the overrides from other apps {% endcomment %}
{{ block.super }}

<script>
const { overrideLocalConfig } = window.__GEONODE_CONFIG__;
window.__GEONODE_CONFIG__.overrideLocalConfig = function(localConfig, _) {

    if (overrideLocalConfig) {
        overrideLocalConfig(localConfig, _)
    }


    // do actual override

    return localConfig;

}

</script>
{% endblock %}
```

If you think, this make sense, I can create a pull request for `geonode-mapstore-client`.

**Comment by mattiagiupponi** [comment]
Hi  @ridoo sorry but today i was busy since yesterday i was OOO.
I'll tag @allyoucanmap and @dsuren1 just to make them provide their opinion on this.

**Comment by ridoo** [comment]
@mattiagiupponi no problem, I hope you enjoyed your free time :)

I referenced my suggestion in [another issue](https://github.com/GeoNode/geonode-mapstore-client/issues/1916). So if @gannebamm tested successfully this one could be merged IMO (did not find any issues, though, I tested this one not thoroughly).

**Comment by mattiagiupponi** [comment]
> @mattiagiupponi no problem, I hope you enjoyed your free time :)
> 
> I referenced my suggestion in [another issue](https://github.com/GeoNode/geonode-mapstore-client/issues/1916). So if @gannebamm tested successfully this one could be merged IMO (did not find any issues, though, I tested this one not thoroughly).

I agree, is better to keep this kind of improvment for later, when it can be well tested in case.
If for @gannebamm everything looks fine, we can merge this PR

**Comment by gannebamm** [comment]
@vineetasharma105 Did you encounter any issues with our latest build? For me it is working well and I would give it a go for merging.

**Comment by gannebamm** [comment]
Hi @mattiagiupponi,
we can assure that the feature is working fine for master. I just tested it locally. For 4.4.x everything works except uploading a dataset from the subsite. You demo in comment https://github.com/geosolutions-it/geonode-subsites/pull/45#issuecomment-2508158386 is using the master branch (you can spot it on the uploaded page with the new css applied). For 4.4.x the route `https://geonode-demo.thuenen.de/holisoils/api/v2/uploads` is not working.

For our use case it is not important, since we will upload ressources from the maint page and *not* via the subsite. In terms of code quality it maybe should get fixed. On the other hand, it is working fine on master 🤷

**Comment by mattiagiupponi** [comment]
> Hi @mattiagiupponi, we can assure that the feature is working fine for master. I just tested it locally. For 4.4.x everything works except uploading a dataset from the subsite. You demo in comment [#45 (comment)](https://github.com/geosolutions-it/geonode-subsites/pull/45#issuecomment-2508158386) is using the master branch (you can spot it on the uploaded page with the new css applied). For 4.4.x the route `https://geonode-demo.thuenen.de/holisoils/api/v2/uploads` is not working.
> 
> For our use case it is not important, since we will upload ressources from the maint page and _not_ via the subsite. In terms of code quality it maybe should get fixed. On the other hand, it is working fine on master 🤷

Thanks for spotting it.
With the last commit https://github.com/geosolutions-it/geonode-subsites/pull/45/commits/e2abe20844da8e281d8e1b576a33c23540d9bcee now the "Add resource" in the subsite works as expected in 44x.
If there are no more bugs and if you give the green line i'll merge the PR :) (feel free to approve it too!)

**Comment by gannebamm** [comment]
Just for the record: We successfully tested the PR :+1:

**Pull request merged**
